/* VSL Forms Warehouse Admin - moved to Gestione Applicazione */
(function(){
  'use strict';
  const client=window.AppSupabase&&window.AppSupabase.getClient?window.AppSupabase.getClient():null;
  const $=id=>document.getElementById(id);
  const norm=v=>String(v||'').trim().toUpperCase();
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  const num=(v,fb=0)=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:fb;};
  const state={user:null,isAdmin:false,rows:[],search:''};
  function show(el,msg,type){if(!el)return;el.textContent=msg;el.className='message '+(type||'info');el.classList.remove('hidden');}
  async function profile(){if(!client)return;const s=await client.auth.getSession();state.user=s?.data?.session?.user||null;if(!state.user){state.isAdmin=false;return;}const r=await client.from('app_users').select('*').eq('user_id',state.user.id).maybeSingle();const p=r.data||{};const role=norm(p.role);state.isAdmin=p.is_active!==false&&(p.can_manage_operators===true||role==='ADMIN'||role==='SUPERADMIN');}
  function view(){const target=$('operatorsAdminView');if(!target||$('formsAdminWarehousePanel'))return;const sec=document.createElement('div');sec.id='formsAdminWarehousePanel';sec.className='card inline-card forms-admin-panel';sec.innerHTML=`<div class="rows-top"><div><h3>Magazzino Forme</h3><p>Area admin: import Excel con sovrascrittura totale. Il magazzino forme viene usato dalla Programmazione per lookup forma/quantità.</p></div><button id="formsAdminRefreshBtn" class="btn btn-secondary" type="button">Aggiorna magazzino</button></div><div class="form-grid form-grid-3"><div class="field"><label>File Excel magazzino forme</label><input id="formsAdminFile" type="file" accept=".xlsx,.xls,.csv"></div><div class="field"><label>&nbsp;</label><button id="formsAdminImportBtn" class="btn btn-primary btn-block" type="button">Sostituisci magazzino forme</button></div><div class="field"><label>Cerca forma</label><input id="formsAdminSearch" type="text" placeholder="MOD, MOD VAR, forma"></div></div><div id="formsAdminStatus" class="message info">Magazzino forme disponibile per lookup programma.</div><div id="formsAdminStats" class="summary-box compact"></div><div class="table-wrap compact-scroll"><table class="attendance-table"><thead><tr><th>Articolo</th><th>MOD VAR</th><th>MOD</th><th>Forma</th><th>TOT</th></tr></thead><tbody id="formsAdminBody"></tbody></table></div>`;target.appendChild(sec);}
  async function ensureXlsx(){if(window.XLSX)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx/dist/xlsx.full.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s);});}
  function get(row,names){const keys=Object.keys(row||{});const clean=v=>norm(v).replaceAll('.','').replaceAll('_',' ').replace(/\s+/g,' ');for(const n of names){const k=keys.find(x=>clean(x)===clean(n));if(k!==undefined)return row[k];}return '';}
  async function load(){if(!client||!state.isAdmin)return;const all=[];let from=0,size=1000;while(true){const r=await client.from('forms_warehouse').select('*').order('article_code',{ascending:true}).range(from,from+size-1);if(r.error){show($('formsAdminStatus'),r.error.message,'error');break;}const c=r.data||[];all.push(...c);if(c.length<size)break;from+=size;if(from>100000)break;}state.rows=all;show($('formsAdminStatus'),'Magazzino forme caricato: '+all.length+' righe.','success');render();}
  async function importFile(){const file=$('formsAdminFile')?.files?.[0];if(!file)return show($('formsAdminStatus'),'Seleziona file Excel magazzino forme.','error');if(!confirm('Sovrascrivere il Magazzino Forme?'))return;await ensureXlsx();const wb=window.XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];const rows=window.XLSX.utils.sheet_to_json(sheet,{defval:''}).map(r=>({article_code:String(get(r,['MOD'])||get(r,['COD. MODELLO'])).trim().toUpperCase(),mod_var:String(get(r,['MOD VAR'])).trim().toUpperCase(),mod:String(get(r,['MOD_1','MOD 1','MOD.1','MOD.2','MOD 2'])).trim().toUpperCase(),cod_model:String(get(r,['COD. MODELLO'])||get(r,['MOD'])).trim().toUpperCase(),model_forma:String(get(r,['MODELLO FORMA'])).trim(),description_forma:String(get(r,['DESCRIZIONE FORMA'])).trim(),total_qty:num(get(r,['TOT']),0),imported_by:state.user.id})).filter(r=>r.cod_model||r.mod_var||r.model_forma);if(!rows.length)return show($('formsAdminStatus'),'Nessuna riga valida trovata.','error');const del=await client.from('forms_warehouse').delete().not('id','is',null);if(del.error)return show($('formsAdminStatus'),del.error.message,'error');for(let i=0;i<rows.length;i+=500){const ins=await client.from('forms_warehouse').insert(rows.slice(i,i+500));if(ins.error)return show($('formsAdminStatus'),ins.error.message,'error');show($('formsAdminStatus'),`Import ${Math.min(i+500,rows.length)}/${rows.length} righe...`,'info');}await load();show($('formsAdminStatus'),'Magazzino forme sostituito: '+rows.length+' righe.','success');}
  function render(){const q=norm(state.search);const rows=state.rows.filter(r=>!q||norm([r.article_code,r.cod_model,r.mod_var,r.mod,r.model_forma,r.description_forma].join(' ')).includes(q));$('formsAdminStats')&&($('formsAdminStats').innerHTML=`<div><span>Forme database</span><strong>${state.rows.length}</strong></div><div><span>Righe filtrate</span><strong>${rows.length}</strong></div>`);$('formsAdminBody')&&($('formsAdminBody').innerHTML=rows.slice(0,500).map(r=>`<tr><td>${esc(r.article_code||r.cod_model||'-')}</td><td>${esc(r.mod_var||'-')}</td><td>${esc(r.mod||'-')}</td><td>${esc(r.model_forma||'-')}</td><td>${esc(r.total_qty??'-')}</td></tr>`).join('')||'<tr><td colspan="5">Nessun dato.</td></tr>');}
  function bind(){const r=$('formsAdminRefreshBtn');if(r&&!r.dataset.formsAdmin){r.dataset.formsAdmin='1';r.onclick=load;}const i=$('formsAdminImportBtn');if(i&&!i.dataset.formsAdmin){i.dataset.formsAdmin='1';i.onclick=importFile;}const s=$('formsAdminSearch');if(s&&!s.dataset.formsAdmin){s.dataset.formsAdmin='1';s.oninput=()=>{state.search=s.value;render();};}}
  async function init(){if(!client)return;await profile();if(!state.isAdmin)return;view();bind();load();}
  document.addEventListener('DOMContentLoaded',()=>{setTimeout(init,1400);setTimeout(init,3000);});
})();
