/* VSL Operations Workforce - Multipage Router V6 */
(function(){
  'use strict';
  var PATHS={dashboard:'index.html',presenze:'pages/presenze.html',assenze:'pages/assenze-programmate.html',riepilogo:'pages/riepilogo-presenze.html',gestione:'pages/gestione-applicazione.html',programmazione:'pages/programmazione.html','tempi-metodi':'pages/tempi-metodi.html'};
  var BOOT={dashboard:['openHomeBtn'],presenze:['openAttendanceBtn','homeOpenAttendanceBtn'],assenze:['openPlannedAbsencesBtn','homeOpenPlannedAbsencesBtn'],riepilogo:['openAttendanceAdminBtn','homeOpenAttendanceAdminBtn'],gestione:['openOperatorsBtn','homeOpenOperatorsBtn'],programmazione:['openProgrammingBtn','homeOpenProgrammingBtn'],'tempi-metodi':['openTempiMetodiBtn','homeOpenTempiMetodiBtn']};
  var NAV={openHomeBtn:'dashboard',openAttendanceBtn:'presenze',homeOpenAttendanceBtn:'presenze',openPlannedAbsencesBtn:'assenze',homeOpenPlannedAbsencesBtn:'assenze',openAttendanceAdminBtn:'riepilogo',homeOpenAttendanceAdminBtn:'riepilogo',openOperatorsBtn:'gestione',homeOpenOperatorsBtn:'gestione',openProgrammingBtn:'programmazione',homeOpenProgrammingBtn:'programmazione',openTempiMetodiBtn:'tempi-metodi',homeOpenTempiMetodiBtn:'tempi-metodi'};
  function page(){return (document.body&&document.body.dataset&&document.body.dataset.page)||'dashboard';}
  function prefix(){return location.pathname.indexOf('/pages/')!==-1?'../':'./';}
  function url(p){return prefix()+(PATHS[p]||PATHS.dashboard);}
  function go(p){if(!p)return;if(p===page()){if(window.VSLMobileMenu&&window.VSLMobileMenu.close)window.VSLMobileMenu.close();return;}location.assign(url(p));}
  function ready(p){if(p==='assenze'){var b=document.getElementById('openPlannedAbsencesBtn')||document.getElementById('homeOpenPlannedAbsencesBtn');return !!(b&&b.dataset&&b.dataset.boundAbs==='1');}if(p==='programmazione'){var bp=document.getElementById('openProgrammingBtn')||document.getElementById('homeOpenProgrammingBtn');return !!(bp&&bp.dataset&&bp.dataset.boundProg==='1');}if(p==='tempi-metodi'){var bt=document.getElementById('openTempiMetodiBtn')||document.getElementById('homeOpenTempiMetodiBtn');return !!(bt&&bt.dataset&&bt.dataset.tm==='1');}return true;}
  function intercept(){document.addEventListener('click',function(e){if(window.__VSL_PAGE_BOOTSTRAPPING__)return;var t=e.target&&e.target.closest?e.target.closest('button'):null;if(!t||!t.id||!NAV[t.id])return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();go(NAV[t.id]);},true);}
  function forceHome(){Object.keys(NAV).forEach(function(id){var el=document.getElementById(id);if(!el)return;el.dataset.pageTarget=NAV[id];if(id.indexOf('homeOpen')===0){el.onclick=function(ev){if(ev){ev.preventDefault();ev.stopPropagation();}go(NAV[id]);return false;};}});}
  function chrome(){var p=page();document.documentElement.dataset.vslPage=p;document.body.dataset.vslPage=p;Object.keys(NAV).forEach(function(id){var el=document.getElementById(id);if(el)el.classList.toggle('is-current-page',NAV[id]===p);});}
  function click(ids){for(var i=0;i<ids.length;i++){var el=document.getElementById(ids[i]);if(el){window.__VSL_PAGE_BOOTSTRAPPING__=true;try{el.click();}finally{setTimeout(function(){window.__VSL_PAGE_BOOTSTRAPPING__=false;},250);}return true;}}return false;}
  function boot(){var p=page(),ids=BOOT[p]||BOOT.dashboard,tries=0,max=180,done=false;var tm=setInterval(function(){tries++;chrome();forceHome();var app=document.getElementById('appSection'),auth=document.getElementById('authSection');var appVis=app&&!app.classList.contains('hidden'),authVis=auth&&!auth.classList.contains('hidden');if(authVis&&!appVis){if(tries>max)clearInterval(tm);return;}if(!ready(p)){if(tries>max)clearInterval(tm);return;}if(!done&&click(ids)){done=true;setTimeout(function(){chrome();forceHome();if(p==='tempi-metodi'){var r=document.getElementById('refreshCycleTimesBtn');if(r)r.click();}},900);clearInterval(tm);return;}if(tries>max)clearInterval(tm);},150);}
  function init(){intercept();chrome();forceHome();boot();setTimeout(chrome,1000);setTimeout(chrome,2500);setTimeout(forceHome,1000);setTimeout(forceHome,2500);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
