/* ===== TEMPI E METODI - ADMIN ===== */
(function(){
  'use strict';
  const client=window.AppSupabase&&window.AppSupabase.getClient?window.AppSupabase.getClient():null;
  const $=(id)=>document.getElementById(id);
  const norm=(v)=>String(v||'').trim().toUpperCase();
  const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  const num=(v,fb=0)=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:fb;};
  const state={user:null,profile:null,isAdmin:false,rows:[],search:'',pageSize:'500'};
  function show(el,msg,type){if(!el)return;el.textContent=msg;el.className='message '+(type||'info');el.classList.remove('hidden');}
  async function profile(){const s=await client.auth.getSession();state.user=s?.data?.session?.user||null;if(!state.user){state.isAdmin=false;return;}const r=await client.from('app_users').select('*').eq('user_id',state.user.id).maybeSingle();state.profile=r.data||{};const role=norm(state.profile.role);state.isAdmin=state.profile.is_active!==false&&(state.profile.can_manage_operators===true||role==='ADMIN'||role==='SUPERADMIN');}
  function nav(){const top=$('topbarMenu');if(top&&!$('openTempiMetodiBtn')){const b=document.createElement('button');b.id='openTempiMetodiBtn';b.className='btn btn-secondary hidden';b.type='button';b.textContent='Tempi e Metodi';top.insertBefore(b,$('openOperatorsBtn')||$('userBadge')||null);b.onclick=open;}const grid=document.querySelector('.home-grid');if(grid&&!$('homeOpenTempiMetodiBtn')){const b=document.createElement('button');b.id='homeOpenTempiMetodiBtn';b.className='home-card admin-only-card hidden';b.type='button';b.innerHTML='<span class="home-card-icon">TM</span><span class="home-card-title">Tempi e Metodi</span><span class="home-card-text">Carica tempi cicli di produzione per saturazione manovia.</span>';grid.appendChild(b);b.onclick=open;}}
  function visible(){$('openTempiMetodiBtn')?.classList.toggle('hidden',!state.isAdmin);$('homeOpenTempiMetodiBtn')?.classList.toggle('hidden',!state.isAdmin);}
  function view(){const app=$('appSection');if(!app||$('tempiMetodiView'))return;const s=document.createElement('section');s.id='tempiMetodiView';s.className='view hidden tempi-metodi-page';s.innerHTML=`<div class="card tempi-metodi-hero"><div class="rows-top"><div><span class="step-badge">Admin</span><h2>Tempi e Metodi</h2><p>Carica il file VSL Bucine - Tempi cicli di lavorazione per articolo, foglio Articoli_lavorazioni. Il caricamento sostituisce il precedente.</p></div><button id="refreshCycleTimesBtn" class="btn btn-secondary" type="button">Aggiorna dati</button></div><div id="tempiMetodiMessage" class="message hidden"></div></div><div class="card inline-card"><div class="rows-top"><div><h3>Articoli lavorazioni tempi cicli di produzione</h3><p>Colonne lette dal foglio Articoli_lavorazioni: Articolo, Test, Fase, Lavorazione, Tempo medio di lavorazione (s). MOD e TEMPO vengono calcolati: TEMPO = Test * Tempo medio * 60 secondi.</p></div><button id="downloadCycleTimesTemplateBtn" class="btn btn-secondary" type="button">Scarica template</button></div><div class="form-grid form-grid-3"><div class="field"><label>File Excel tempi</label><input id="cycleTimesFile" type="file" accept=".xlsx,.xls,.xlsm,.csv"></div><div class="field"><label>&nbsp;</label><button id="importCycleTimesBtn" class="btn btn-primary btn-block" type="button">Sostituisci tabella tempi</button></div><div class="field"><label>Filtri import</label><label><input id="excludeTestZero" type="checkbox" checked> Escludi TEST=0</label><label><input id="excludeNonProductivePhases" type="checkbox" checked> Escludi fasi non produttive</label></div><div class="field"><label>Cerca</label><input id="cycleTimesSearch" type="text" placeholder="Articolo, MOD, fase"></div></div><div id="cycleTimesStatus" class="message info">Database tempi in caricamento...</div><div id="cycleTimesStats" class="summary-box compact"></div><div><select id="cycleTimesPageSize"><option>100</option><option selected>500</option><option>1000</option><option>5000</option><option value="all">Tutte</option></select></div><div class="table-wrap compact-scroll"><table class="attendance-table"><thead><tr><th>Articolo</th><th>MOD</th><th>Test 2</th><th>Fase</th><th>Lavorazione</th><th>Tempo std s</th><th>TEMPO s</th></tr></thead><tbody id="cycleTimesBody"></tbody></table></div></div>`;app.appendChild(s);}
  function switchView(){['homeView','attendanceView','plannedAbsencesView','operatorsAdminView','attendanceAdminView','programmingView','tempiMetodiView'].forEach(id=>$(id)?.classList.toggle('hidden',id!=='tempiMetodiView'));}
  function bind(){const m={refreshCycleTimesBtn:load,importCycleTimesBtn:importFile,downloadCycleTimesTemplateBtn:template};Object.keys(m).forEach(id=>{const el=$(id);if(el&&el.dataset.tm!=='1'){el.dataset.tm='1';el.onclick=m[id];}});const search=$('cycleTimesSearch');if(search&&search.dataset.tm!=='1'){search.dataset.tm='1';search.oninput=()=>{state.search=search.value;render();};}}
  async function open(){await profile();visible();if(!state.user)return show($('globalMessage'),'Effettua login.','error');if(!state.isAdmin)return show($('globalMessage'),'Sezione riservata admin.','error');view();bind();switchView();await load();}
  async function xlsx(){if(window.XLSX)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx/dist/xlsx.full.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s);});}
  function get(row,names){const keys=Object.keys(row||{});const clean=v=>norm(v).replaceAll('.','').replaceAll('_',' ').replace(/\s+/g,' ');for(const n of names){const k=keys.find(x=>clean(x)===clean(n));if(k!==undefined)return row[k];}return '';}
  function map(r){const articolo=String(get(r,['Articolo'])||'').trim().toUpperCase();const test=num(get(r,['Test','Test 2','Test2']),0);const fase=String(get(r,['Fase'])||'').trim();const lavorazione=String(get(r,['Lavorazione'])||'').trim();const std=num(get(r,['Tempo medio di lavorazione (s)','Media di tempo standard su totale (s)','Tempo standard','Tempo std']),0);return{articolo,test_2:test,fase,lavorazione,tempo_standard_sec:std,mod:articolo.substring(0,3),tempo_sec:std*60*test,imported_by:state.user.id};}
  async function importFile(){const file=$('cycleTimesFile')?.files?.[0];if(!file)return show($('cycleTimesStatus'),'Seleziona il file VSL Bucine - Tempi cicli di lavorazione per articolo.','error');if(!confirm('Confermi? La tabella tempi precedente verra sostituita.'))return;await xlsx();const wb=window.XLSX.read(await file.arrayBuffer(),{type:'array'});const wanted='Articoli_lavorazioni';const sheetName=wb.SheetNames.find(n=>norm(n)===norm(wanted))||wb.SheetNames[0];if(!sheetName)return show($('cycleTimesStatus'),'Nessun foglio trovato nel file.','error');if(norm(sheetName)!==norm(wanted))show($('cycleTimesStatus'),`Foglio Articoli_lavorazioni non trovato: uso il primo foglio ${sheetName}.`,'info');else show($('cycleTimesStatus'),'Leggo il foglio Articoli_lavorazioni...','info');const rows=window.XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:''}).map(map).filter(r=>r.articolo&&r.fase);if(!rows.length)return show($('cycleTimesStatus'),'Nessuna riga valida trovata. Controlla le colonne Articolo, Test, Fase, Lavorazione, Tempo medio di lavorazione (s).','error');const del=await client.from('production_cycle_times').delete().not('id','is',null);if(del.error)return show($('cycleTimesStatus'),del.error.message,'error');for(let i=0;i<rows.length;i+=500){const ins=await client.from('production_cycle_times').insert(rows.slice(i,i+500));if(ins.error)return show($('cycleTimesStatus'),ins.error.message,'error');show($('cycleTimesStatus'),`Import ${Math.min(i+500,rows.length)}/${rows.length} righe dal foglio ${sheetName}...`,'info');}await load();show($('cycleTimesStatus'),'Import completato: '+rows.length+' righe salvate su Supabase','success');}
  async function load(){const all=[];let from=0;const size=1000;while(true){const r=await client.from('production_cycle_times').select('*').order('articolo',{ascending:true}).range(from,from+size-1);if(r.error){state.rows=[];show($('cycleTimesStatus'),r.error.message,'error');render();return;}const chunk=r.data||[];all.push(...chunk);if(chunk.length<size)break;from+=size;if(from>100000)break;}state.rows=all;show($('cycleTimesStatus'),'Database tempi caricato correttamente: '+all.length+' righe presenti su Supabase','success');render();}
  function render(){const q=norm(state.search);const rows=state.rows.filter(r=>!q||norm([r.articolo,r.mod,r.fase,r.lavorazione].join(' ')).includes(q));$('cycleTimesStats')&&($('cycleTimesStats').innerHTML=`<div><span>Righe database</span><strong>${state.rows.length}</strong></div><div><span>Righe filtrate</span><strong>${rows.length}</strong></div><div><span>Fasi usate saturazione</span><strong>Caricamento, Montaggio, Prep. suolatura, Suolatura</strong></div>`);$('cycleTimesBody')&&($('cycleTimesBody').innerHTML=(state.pageSize==='all'?rows:rows.slice(0,parseInt(state.pageSize))).map(r=>`<tr><td>${esc(r.articolo)}</td><td>${esc(r.mod)}</td><td>${esc(r.test_2)}</td><td>${esc(r.fase)}</td><td>${esc(r.lavorazione)}</td><td>${esc(r.tempo_standard_sec)}</td><td>${esc(r.tempo_sec)}</td></tr>`).join('')||'<tr><td colspan="7">Nessun dato.</td></tr>');}
  function template(){downloadCsv('template_tempi_metodi.csv',[['Articolo','Test','Fase','Lavorazione','Tempo medio di lavorazione (s)'],['393AMX',1,'Controllo semilavorati','Controllare la tomaia',72]]);}
  function downloadCsv(name,rows){const csv=rows.map(r=>r.map(c=>'"'+String(c??'').replaceAll('"','""')+'"').join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function init(){if(!client)return;nav();view();bind();await profile();visible();setTimeout(async()=>{await profile();visible();},1200);}document.addEventListener('DOMContentLoaded',init);
})();
